<?php
return [
    [
        'id' => 1,
        'logo' => '/images/logos/Afrinova-Logo.png',
        'mocap' => '/images/mocaps/afrinova.jpeg',
        'name' => 'Afrinova',
        'category' => 'Business',
        'client' => 'Afrinova Consulting',
        'date' => '12/1/18',
        'website' => 'https://afrinova.co.ke/',
        'services' => 'Web Development, UX Design',
        'desc' => 'The best office seat from Demax Ltd is designed to provide exceptional comfort and support for long hours of sitting. With a fully adjustable ergonomic design, it helps to reduce strain on the back, neck and shoulders. Its high-quality materials ensure durability and the sleek design fits perfectly in any office environment. Trust Demax Ltd for the ultimate seating solution.',
        'desc2' => 'In addition, the Demax Ltd office seat also boasts a range of features, including a tilting mechanism, adjustable armrests, and a breathable mesh backrest, all of which contribute to an optimal seating experience. Its easy-to-use controls make it effortless to customize your seating position, while its sleek and modern design will elevate the look of any office. Demax Ltd is committed to providing the best seating solution for your workspace.'
    ],
    [
        'id' => 2,
        'logo' => '/images/logos/instalogo.jpg',
        'mocap' => '/images/mocaps/insta-pumps.jpeg',
        'name' => 'Insta Pumps',
        'category' => 'Engineering',
        'client' => 'INSTA-PUMPS Group LLC',
        'date' => '12/1/18',
        'website' => 'https://insta-pumps.com/',
        'services' => 'Web Development, UX Design',
        'desc' => 'INSTA-PUMPS Group LLC offers Borehole drilling capabilities with solar overlays in pumping systems. Comprising of Project Managers, Drilling personnel; Pumps services Technicians, Test Pumping operators, Electrical & Mechanical Engineers, Civil Engineers / Agricultural, Irrigation Engineers and Workshop Fabrication Technicians.',
        'desc2' => 'INSTA-PUMPS Engineering is a private Firm in operation since October 1996. We supply equipment to private and corporate clients, government institutions and N.g.os in small scale holder Irrigation schemes, domestic Borehole water supplies and remedial repairs on pump sets/ construction of plumbing and civil drainage structures.'
    ],
    [
        'id' => 3,
        'logo' => '/images/logos/South-South-Biogas.png',
        'mocap' => '/images/mocaps/south-south-biogas.jpeg',
        'name' => 'South-south-Biogas',
        'category' => 'Fuels',
        'client' => 'Nairobi, kenya',
        'date' => '12/1/18',
        'website' => 'https://ssbcommunity.org/',
        'services' => 'Web Development, UX Design',
        'desc' => 'The best office seat from Demax Ltd is designed to provide exceptional comfort and support for long hours of sitting. With a fully adjustable ergonomic design, it helps to reduce strain on the back, neck and shoulders. Its high-quality materials ensure durability and the sleek design fits perfectly in any office environment. Trust Demax Ltd for the ultimate seating solution.',
        'desc2' => 'In addition, the Demax Ltd office seat also boasts a range of features, including a tilting mechanism, adjustable armrests, and a breathable mesh backrest, all of which contribute to an optimal seating experience. Its easy-to-use controls make it effortless to customize your seating position, while its sleek and modern design will elevate the look of any office. Demax Ltd is committed to providing the best seating solution for your workspace.'
    ],
    [
        'id' => 4,
        'logo' => '/images/logos/Sunsera_Logo-01.png',
        'mocap' => '/images/mocaps/sunsera.jpeg',
        'name' => 'Sunsera',
        'category' => 'Realtors',
        'client' => 'Sunsera Realtors',
        'date' => '12/1/18',
        'website' => 'https://sunserarealtors.co.ke/',
        'services' => 'Web Development, UX Design',
        'desc' => 'The best office seat from Demax Ltd is designed to provide exceptional comfort and support for long hours of sitting. With a fully adjustable ergonomic design, it helps to reduce strain on the back, neck and shoulders. Its high-quality materials ensure durability and the sleek design fits perfectly in any office environment. Trust Demax Ltd for the ultimate seating solution.',
        'desc2' => 'In addition, the Demax Ltd office seat also boasts a range of features, including a tilting mechanism, adjustable armrests, and a breathable mesh backrest, all of which contribute to an optimal seating experience. Its easy-to-use controls make it effortless to customize your seating position, while its sleek and modern design will elevate the look of any office. Demax Ltd is committed to providing the best seating solution for your workspace.'
    ],
    [
        'id' => 5,
        'logo' => '/images/logos/Timo Fresh Logo.png',
        'mocap' => '/images/mocaps/timo-fresh.jpeg',
        'name' => 'Timo Fresh',
        'category' => 'Fruits, Vegs, nuts',
        'client' => 'Tmo fresh (Extra fine)',
        'date' => '12/1/18',
        'website' => 'https://timofresh.co.uk/',
        'services' => 'Web Development, UX Design',
        'desc' => 'The best office seat from Demax Ltd is designed to provide exceptional comfort and support for long hours of sitting. With a fully adjustable ergonomic design, it helps to reduce strain on the back, neck and shoulders. Its high-quality materials ensure durability and the sleek design fits perfectly in any office environment. Trust Demax Ltd for the ultimate seating solution.',
        'desc2' => 'In addition, the Demax Ltd office seat also boasts a range of features, including a tilting mechanism, adjustable armrests, and a breathable mesh backrest, all of which contribute to an optimal seating experience. Its easy-to-use controls make it effortless to customize your seating position, while its sleek and modern design will elevate the look of any office. Demax Ltd is committed to providing the best seating solution for your workspace.'
    ],
    [
        'id' => 6,
        'logo' => '/images/logos/choicelogo.png',
        'mocap' => '/images/mocaps/choice.jpeg',
        'client' => 'Choice Mobilities',
        'name' => 'Choice Mobilities',
        'date' => '12/1/18',
        'category' => 'Healthcare',
        'website' => 'https://choicemobilities.com/',
        'services' => 'Web Development, UX Design',
        'desc' => 'The best office seat from Demax Ltd is designed to provide exceptional comfort and support for long hours of sitting. With a fully adjustable ergonomic design, it helps to reduce strain on the back, neck and shoulders. Its high-quality materials ensure durability and the sleek design fits perfectly in any office environment. Trust Demax Ltd for the ultimate seating solution.',
        'desc2' => 'In addition, the Demax Ltd office seat also boasts a range of features, including a tilting mechanism, adjustable armrests, and a breathable mesh backrest, all of which contribute to an optimal seating experience. Its easy-to-use controls make it effortless to customize your seating position, while its sleek and modern design will elevate the look of any office. Demax Ltd is committed to providing the best seating solution for your workspace.'
    ],
    [
        'id' => 7,
        'logo' => '/images/logos/jts-logo.jpeg',
        'mocap' => '/images/mocaps/jts.jpeg',
        'name' => 'Jts Service',
        'category' => 'Multimedia',
        'client' => 'Jts Service',
        'date' => '12/1/18',
        'website' => 'https://jtsservice.com/',
        'services' => 'Web Development, UX Design',
        'desc' => 'The best office seat from Demax Ltd is designed to provide exceptional comfort and support for long hours of sitting. With a fully adjustable ergonomic design, it helps to reduce strain on the back, neck and shoulders. Its high-quality materials ensure durability and the sleek design fits perfectly in any office environment. Trust Demax Ltd for the ultimate seating solution.',
        'desc2' => 'In addition, the Demax Ltd office seat also boasts a range of features, including a tilting mechanism, adjustable armrests, and a breathable mesh backrest, all of which contribute to an optimal seating experience. Its easy-to-use controls make it effortless to customize your seating position, while its sleek and modern design will elevate the look of any office. Demax Ltd is committed to providing the best seating solution for your workspace.'
    ],
];
